### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by bkeepers**
## Inchworm Image Optimization Summary

Inchworm optimized 28 images for a total savings of 2.1 MB (42.7%).

| Image | Original | Optimized | Savings | % |
|:--- | ---:| ---:| ---:| ---:|
| _assets/images/jshint.png | 309 KB | 186 KB | 123 KB | 39.6% |
| _site/deployed/assets/screen_shot_20120111_at_3.50.09_pm-d2b05de7416d984854aca0f712817942.png | 172 KB | 112 KB | 59.9 KB | 34.8% |
| _site/deployed/assets/Screen_Shot_2013_01_05_at_11_53_17_PM-d08892b5fc4cf9508faf25b70ace657a.png | 310 KB | 206 KB | 104 KB | 33.5% |
| _site/deployed/assets/olctocat-a90d74a770db857f1da975b23c2e4983.png | 60.4 KB | 37.5 KB | 22.8 KB | 37.8% |
| _site/deployed/assets/screen_shot_20120112_at_8.03.54_am-5c91715bfe5be523146765a3e3d20ceb.png | 20.8 KB | 9.55 KB | 11.2 KB | 54.1% |
| _site/deployed/assets/scrollbar-2307b9903c082867567b6fe110143f18.png | 179 B | 94 B | 85 B | 47.5% |
| _site/deployed/assets/screen_shot_20120111_at_4.55.08_pm-2da009b991a289bd8f84272e0b457569.png | 15.7 KB | 7.78 KB | 7.9 KB | 50.4% |
| _site/deployed/assets/screen_shot_20120111_at_2.15.34_pm-7d76fb9291b60d48c6ada4e3096be17b.png | 91 KB | 57.3 KB | 33.7 KB | 37.0% |
| _site/deployed/assets/img_5072-b87197fa6b139e699d6a45f284073cd0.jpg | 166 KB | 161 KB | 5.3 KB | 3.2% |
| _site/deployed/assets/jshint-4660a3c72097cbb24c21a01dd6578901.png | 309 KB | 186 KB | 123 KB | 39.6% |
| _site/deployed/assets/img_5070-5503b5486f41267207595e0fdb30efd9.jpg | 258 KB | 253 KB | 5.17 KB | 2.0% |
| _assets/images/screen_shot_20120111_at_4.55.08_pm.png | 15.7 KB | 7.78 KB | 7.9 KB | 50.4% |
| _site/deployed/assets/IMG_0021-a05d937d9839cfcc18a50bac3cabab6b.PNG | 110 KB | 83.8 KB | 26.6 KB | 24.1% |
| _site/deployed/assets/IMG_0019-c8b3f09abdc87592a5502c8963743147.PNG | 28.3 KB | 9.93 KB | 18.4 KB | 64.9% |
| _site/deployed/assets/IMG_0004_2-8734fa7ff2b0b13492e48bba834b5e00.jpg | 152 KB | 148 KB | 3.81 KB | 2.5% |
| _site/deployed/assets/IMG_0002_2-fb419d026857ad7551fb73cb4430f8b9.jpg | 169 KB | 164 KB | 4.08 KB | 2.4% |
| _assets/images/screen_shot_20120112_at_8.03.54_am.png | 20.8 KB | 9.55 KB | 11.2 KB | 54.1% |
| _assets/images/scrollbar.png | 179 B | 94 B | 85 B | 47.5% |
| _assets/images/olctocat.png | 60.4 KB | 37.5 KB | 22.8 KB | 37.8% |
| _assets/images/screen_shot_20120111_at_2.15.34_pm.png | 91 KB | 57.3 KB | 33.7 KB | 37.0% |
| _assets/images/screen_shot_20120111_at_3.50.09_pm.png | 172 KB | 112 KB | 59.9 KB | 34.8% |
| _assets/images/IMG_0002_2.jpg | 169 KB | 164 KB | 4.08 KB | 2.4% |
| _assets/images/img_5073.jpg | 162 KB | 158 KB | 4.78 KB | 2.9% |
| _assets/images/img_5072.jpg | 166 KB | 161 KB | 5.3 KB | 3.2% |
| _assets/images/img_5070.jpg | 258 KB | 253 KB | 5.17 KB | 2.0% |
| _assets/images/Screen_Shot_2013_01_05_at_11_53_17_PM.png | 310 KB | 206 KB | 104 KB | 33.5% |
| _assets/images/IMG_0021.PNG | 110 KB | 83.8 KB | 26.6 KB | 24.1% |
| _assets/images/IMG_0019.PNG | 28.3 KB | 9.93 KB | 18.4 KB | 64.9% |

### CODE REVIEW

**Comment by bkeepers** [comment]
http://38.media.tumblr.com/047a2942dd09d010368ebfafa8731c97/tumblr_mskrh1AWCe1ry46hlo1_r1_400.gif

/cc @laserlemon @danielmorrison

**Comment by laserlemon** [comment]
:tada:

**Comment by danielmorrison** [comment]
Too bad GitHub only shows diffs for the first 25 images :cry:

**Pull request merged**
