### PR TITLE
What are some examples of open source software that most people have heard of?

### PR DESCRIPTION
**Pull request by bkeepers**
Here are a few to start, but what other open source projects are popular among common folks?

/cc @benbalter

### CODE REVIEW

**Comment by benbalter** [comment]
* Android
* MySQL
* Apache
* Drupal

Also things that are proprietary, but use open source heavily:

* Your phone 
* Your car
* Your TV

(Hit about -> licenses to see all the open source projects embedded in every day things)

**Comment by bkeepers** [comment]
> Android

Good call! Although it will have a very large asterisk next to it :trollface: 

> MySQL
> Apache
> Drupal

I should clarify in the post that the context was looking for examples that non-technical people would know about. Drupal might make the cut, but I think the other ones probably don't.

**Comment by willnorris** [comment]
Wikipedia (okay, technically MediaWiki)

**Comment by willnorris** [comment]
Might be worth just adding a sentence to mention how many embedded devices also run Linux (TVs, cable boxes, routers, etc).  People have not just interacted with Linux if they use the internet, but they quite possibly have it running somewhere in their house.

**Comment by bkeepers** [comment]
> Might be worth just adding a sentence to mention how many embedded devices also run Linux (TVs, cable boxes, routers, etc). People have not just interacted with Linux if they use the internet, but they quite possibly have it running somewhere in their house.

Good call https://github.com/bkeepers/bkeepers.github.io/commit/61d6d8e7e312010eb38f4e21cb144424697f58e2

**Pull request merged**
